In [6]:
import pandas as pd

In [9]:
data = pd.read_csv("Churn_Modelling.csv")

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [17]:
data.Gender.value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [18]:
from pycaret.classification import *

In [19]:
s = setup(data, target = 'Exited', ignore_features = ['CustomerId', 'Surname', 'RowNumber'])

In [20]:
best_model = compare_models(sort='Recall')